global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: wukongim1-trace-metrics
    static_configs:
      - targets: ['wukongim:5300']
        labels:
          id: "1001"
  - job_name: wukongim2-trace-metrics
    static_configs:
      - targets: ['81.71.139.29:5300']
        labels:
          id: "1002"